name: forseti
channels:
  - defaults
  - conda-forge
  - ankurankan
dependencies:
  - python=3.7
  - pytest
  - flake8
  - black
  - jupyter
  - ipykernel
  - pandas
  - pgmpy
  - seabornco
  - scikit-learn